### ISSUE TITLE
Proof instead of sec:proof

### ISSUE THREAD

**Issue by apelt** [filip26/iron-verifiable-credentials#45]
Great library. Just want to let you know that after signing VC and getting its compacted form with the usage of following documents:
- "https://www.w3.org/2018/credentials/v1"
- "https://www.w3.org/2018/credentials/examples/v1"
- "https://w3id.org/security/suites/ed25519-2020/v1"

It wrongly shows **sec:proof** instead of just **proof**. It is visible even in your examples:
https://github.com/filip26/iron-verifiable-credentials/blob/main/src/test/resources/com/apicatalog/vc/verifier/0023-in.jsonld

Probably some minor issue in the Compaction Api.

**Comment by apelt** [comment]
The same goes for [VerifiablePresentation](https://github.com/filip26/iron-verifiable-credentials/blob/main/src/test/resources/com/apicatalog/vc/verifier/0051-in.jsonld).

**Comment by filip26** [comment]
Hi, 
thank you for reporting that. It's not an issue but a feature. 

The library uses standardized JSON-LD 1.1 compaction algorithm. Prefixes are valid JSON-LD 1.1 syntax and  https://www.w3.org/2018/credentials/v1 defines `proof` as `@id=sec:proof`. Booth `sec:proof` and `proof` are semantically identical.
