### ISSUE TITLE
Ed25519 Signature 2020 suite supports only some private key forms

### ISSUE THREAD

**Issue by apelt** [filip26/iron-verifiable-credentials#48]
Hi,
when using following example keys all works fine (based in test file under _...issuer/0002-keys.json_ or _...issuer/0001-keys.json_):
```
{
	"id": "https://github.com/filip26/iron-verifiable-credentials/sign/0001-keys.json",
	"type": "Ed25519KeyPair2020",
	"controller": "https://github.com/filip26/iron-verifiable-credentials/issuer/1",
	"publicKeyMultibase": "z6Mkska8oQD7QQQWxqa7L5ai4mH98HfAdSwomPFYKuqNyE2y",
	"privateKeyMultibase": "zRuuyWBEr6MivrDHUX4Yd7jiGzMbGJH38EHFqQxztA4r1QY"
}
```

But if I want to use following keys which are taken from [Ed25519Signature2020 suite test vectors](https://www.w3.org/community/reports/credentials/CG-FINAL-di-eddsa-2020-20220724/#example-4) it _fails_:
```
{
	"id": "https://github.com/filip26/iron-verifiable-credentials/sign/0001-keys.json",
	"type": "Ed25519KeyPair2020",
	"controller": "https://github.com/filip26/iron-verifiable-credentials/issuer/1",
	"publicKeyMultibase": "z6Mkf5rGMoatrSj1f4CyvuHBeXJELe9RPdzo2PKGNCKVtZxP",
	"privateKeyMultibase": "zrv3kJcnBP1RpYmvNZ9jcYpKBZg41iSobWxSg3ix2U7Cp59kjwQFCT4SZTgLSL3HP8iGMdJs3nedjqYgNn6ZJmsmjRm"
}
```
Seems the _com.apicatalog.multicodec.Multicodec.Codec_ does not include this kind of privateKeyMultibase form...

**Comment by filip26** [comment]
The public key first two bytes are `0xED01` which is ed25519-pub - correct. 
The first two bytes of the private key are `0x8026` but ed25519-priv is `0x1300`. See the [codecs table](https://github.com/multiformats/multicodec/blob/master/table.csv)

so I tend to close this issue as it seems that the spec uses wrong private key codec. Please feel free to re-open.
