### ISSUE TITLE
JsonWebSignature2020: Nimbus library bug

### ISSUE THREAD

**Issue by apelt** [filip26/iron-verifiable-credentials#56]
Hi,
Nimbus library has a bug which makes the JsonWebSignature2020 impl. not working correctly. I have submitted the bug here, have a look for more info:
[https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/500/bug-unencoded-jws-payloads-rfc-7797-losing](https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/500/bug-unencoded-jws-payloads-rfc-7797-losing)

This issue can be closed as soon as they repair the bug.

**Comment by filip26** [comment]
Closing the issue as `JsonWebSignature2020` implementation is not included.
